name: 🧠 Deploy Staging

on:
  push:
    branches: [staging]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci && npm run build
      - name: Deploy to S3 (staging)
        run: aws s3 sync dist/ s3://${{ secrets.STAGING_BUCKET }} --delete
